# Generated by Django 4.2.3 on 2023-08-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jsonfile',
            unique_together={('name', 'subfolder')},
        ),
    ]
